### ISSUE TITLE
date wrong

### ISSUE THREAD

**Issue by hsamarco** [jlgrimes/hads-bot#1] opened 2021-04-21 21:05 UTC
hey ur code is wrong pls fix thanks

**Comment by jlgrimes** [comment] 2021-04-21 21:06
Hi Hadley,

Can you please provide more details?

Thanks,
Jared

**Comment by hsamarco** [comment] 2021-04-21 21:08
Hi Jared,

I don't think you know how to count.

Sincerely,
Hadley <3

**Comment by jlgrimes** [comment] 2021-04-21 21:08
Hey Hadley,

I’d appreciate it if we could find a root cause to this. I’ll ask once more, what is the specific issue you’re experiencing?

**Comment by hsamarco** [comment] 2021-04-21 21:10
Hello Jared.

Your program does not output the correct time difference it is advertised to. This a misleading and potentially harmful error and should be addressed immediately. Please review your code and see if there is any way to fix this.

Thanks.
Hadley

**Comment by jlgrimes** [comment] 2021-04-21 21:29
Hey Hadley,

I attempted to fix it. If it doesn't work, that's too bad.

https://github.com/jlgrimes/hads-bot/commit/a97dea164bb9c688c7ea6761724cc04e876e92e5#diff-55b37cb8dec2eb83ee249d13c8cea6fdb904ddb311d6cf0c981eed5cbd6860b2

Resolving.

**Closed as completed by jlgrimes** 2021-04-21 21:29 UTC
